### PR TITLE
Fix compilation failure on Debian Squeeze (and perhaps Ubuntu 10.04)

### PR DESCRIPTION
**Pull request by Jalle19**
Debian Squeeze ships with an outdated version of libgtk2.0-dev. Sometime between Squeeze's release and today the naming convention in gdk/gdkkeysyms.h changed which means Phoenix won't compile on Squeeze without this patch. It's not particularly pretty but it does the job.

### CODE REVIEW

**Comment by Themaister** [comment]
Defines like that don't belong deep into a .cpp file. Try to move it to where GTK headers are included (phoenix headers somewhere).

**Comment by Jalle19** [comment]
I'm not really sure if this is the right location either since there are includes both in the headers and the source files.

**Comment by Themaister** [comment]
What about in PHOENIX_GTK #ifdef in phoenix.cpp? GTK headers are included there.

**Comment by Jalle19** [comment]
I moved the defines to the location you hinted at and squashed the commits.

**Pull request merged**
